"""
crypto.py  --  Data protection for genome payloads.

THREAT MODEL (read this — it sets honest expectations).
A report is only generated by decrypting the user's genome and annotating it,
so the worker MUST see the plaintext genome in memory. True zero-knowledge,
client-holds-the-only-key E2E is therefore impossible for the annotation step.
What we CAN guarantee, and do here:

  * In transit ............ TLS everywhere (Railway terminates HTTPS; Microsoft
                            Graph is HTTPS). Genome never crosses a network in
                            the clear.
  * At rest in the queue .. The job payload (genome text) is encrypted with
                            authenticated AES-256-GCM before it is ever written
                            to Redis. A Redis dump, a compromised broker, or a
                            backup leak yields only ciphertext.
  * In processing ......... The worker decrypts into memory only. No plaintext
                            genome and no PDF is ever written to disk (the new
                            pipeline is fully in-memory), so nothing to scrub.
  * Optional client-side .. A browser may additionally seal the genome to the
                            server's X25519 public key BEFORE upload (sealed
                            box). Then the upload body is opaque to any proxy,
                            CDN, or request log, and only this server's private
                            key can open it. This is the strongest practical
                            posture short of doing genomics in the browser.

KEYS (set in Railway env, never in code):
  GENODYN_DATA_KEYS   comma-separated base64 AES-256 keys (32 bytes each).
                      First key encrypts; all keys are tried for decrypt, so you
                      can rotate by prepending a new key and removing old ones
                      later. Generate one with:  python -m services.crypto keygen
  GENODYN_X25519_PRIV base64 X25519 private key for the optional sealed-box
                      upload path. Generate with: python -m services.crypto x25519
"""
import os
import base64

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.asymmetric.x25519 import (
    X25519PrivateKey, X25519PublicKey)
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes

_MAGIC = b"GDX1"          # versioned envelope prefix (symmetric)
_SEAL_MAGIC = b"GDXS"     # versioned envelope prefix (sealed box)


# ----------------------------------------------------------- symmetric (at rest)

def _load_keys():
    raw = os.environ.get("GENODYN_DATA_KEYS", "")
    keys = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        k = base64.urlsafe_b64decode(part + "=" * (-len(part) % 4))
        if len(k) != 32:
            raise ValueError("each GENODYN_DATA_KEYS entry must decode to 32 bytes")
        keys.append(k)
    return keys


def encryption_enabled():
    return bool(os.environ.get("GENODYN_DATA_KEYS", "").strip())


def encrypt(data: bytes, aad: bytes = b"genome") -> bytes:
    """Authenticated AES-256-GCM. Returns MAGIC || nonce(12) || ciphertext+tag.

    If no key is configured this returns the data unchanged (with a distinct
    prefix) so local dev still works; production MUST set GENODYN_DATA_KEYS."""
    keys = _load_keys()
    if not keys:
        return b"PLAIN" + data
    nonce = os.urandom(12)
    ct = AESGCM(keys[0]).encrypt(nonce, data, aad)
    return _MAGIC + nonce + ct


def decrypt(token: bytes, aad: bytes = b"genome") -> bytes:
    if token.startswith(b"PLAIN"):
        return token[5:]
    if not token.startswith(_MAGIC):
        raise ValueError("unrecognized envelope")
    nonce, ct = token[4:16], token[16:]
    last = None
    for k in _load_keys():
        try:
            return AESGCM(k).decrypt(nonce, ct, aad)
        except Exception as e:               # try the next (rotation) key
            last = e
    raise ValueError(f"decrypt failed under all configured keys: {last}")


# ------------------------------------------------------- sealed box (optional)
# Anonymous sender -> server. Client generates an ephemeral X25519 keypair,
# derives a shared secret with the server's public key via HKDF, and AESGCMs
# the genome. Only the server's private key can recover it.

def server_public_key_b64() -> str:
    priv_b64 = os.environ.get("GENODYN_X25519_PRIV", "").strip()
    if not priv_b64:
        return ""
    priv = X25519PrivateKey.from_private_bytes(
        base64.urlsafe_b64decode(priv_b64 + "=" * (-len(priv_b64) % 4)))
    from cryptography.hazmat.primitives import serialization
    pub = priv.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw)
    return base64.urlsafe_b64encode(pub).decode()


def _hkdf(shared: bytes) -> bytes:
    return HKDF(algorithm=hashes.SHA256(), length=32,
                salt=None, info=b"genodyn-sealed-box").derive(shared)


def open_sealed(token: bytes) -> bytes:
    """Open a sealed-box upload: SEAL_MAGIC || eph_pub(32) || nonce(12) || ct."""
    if not token.startswith(_SEAL_MAGIC):
        raise ValueError("not a sealed-box payload")
    priv_b64 = os.environ["GENODYN_X25519_PRIV"].strip()
    priv = X25519PrivateKey.from_private_bytes(
        base64.urlsafe_b64decode(priv_b64 + "=" * (-len(priv_b64) % 4)))
    eph_pub = X25519PublicKey.from_public_bytes(token[4:36])
    nonce, ct = token[36:48], token[48:]
    key = _hkdf(priv.exchange(eph_pub))
    return AESGCM(key).decrypt(nonce, ct, b"sealed")


def is_sealed(token: bytes) -> bool:
    return token.startswith(_SEAL_MAGIC)


# ---------------------------------------------------------------------- CLI
if __name__ == "__main__":
    import sys
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "keygen":
        print(base64.urlsafe_b64encode(os.urandom(32)).decode())
    elif cmd == "x25519":
        from cryptography.hazmat.primitives import serialization
        priv = X25519PrivateKey.generate()
        pb = priv.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption())
        pubb = priv.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw)
        print("GENODYN_X25519_PRIV =", base64.urlsafe_b64encode(pb).decode())
        print("public key (give to frontend) =",
              base64.urlsafe_b64encode(pubb).decode())
    else:
        print("usage: python -m services.crypto [keygen|x25519]")
